version: 0.2

env:
  variables:
    SOURCE_VERSION: ""
phases:
  install:
    commands:
      - echo $SOURCE_VERSION Branch Welcome  to Codebuild ! install phase...
      - echo "testing webhook second time"
      - echo "testing webhook testing time"
      - echo "webhook testing"
  pre_build:
    commands:
      - echo $SOURCE_VERSION Branch ! pre_build phase...
  build:
    commands:
      - echo $SOURCE_VERSION Branch ! Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo $SOURCE_VERSION Branch ! Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
  discard-paths: yes
