version: 0.2

phases:
  install:
    commands:
      - echo This is develop Branch ...
  pre_build:
    commands:
      - echo This is develop Branch Nothing to do in the pre_build phase...
  build:
    commands:
      - echo This is develop Branch Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo This is develop Branch Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
