version: 0.2

env:
  variables:
      BRANCH_NAME: ""
phases:
  install:
    commands:
      - echo $BRANCH_NAME Branch ! install phase...
  pre_build:
    commands:
      - echo $BRANCH_NAME Branch ! pre_build phase...
  build:
    commands:
      - echo $BRANCH_NAME Branch ! Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo $BRANCH_NAME Branch ! Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
  discard-paths: yes

